use_frameworks!

platform :ios, '9.0'

target 'HZHelloWorld_Example' do
  pod 'HZHelloWorld', :path => '../'

  target 'HZHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
